trellowatch/apps/watcher/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from . import views

app_name = "watcher"

urlpatterns = [
    url(r'^board_list/$', views.board_list, name='board_list'),
    url(r'^trello_task/$', views.trello_task, name='trello_task'),
    url(r'^update_watched_boards/$', views.update_watched_boards, name='update_watched_boards'),
    url(r'^generate_board_list/$', views.generate_board_list, name='generate_board_list'),
    url(r'^mute_this_task/(?P<task_id>\w+)', views.mute_this_task, name='mute_this_task'),
    url(r'^trelloCallback/(?P<user_id>\w+)', views.trello_webhook, name='trello_webhook'),
]

trellowatch/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from . import views
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^watcher/', include('watcher.urls')),
    url(r'^$', views.home, name='home'),
    url('', include('social_django.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),

]

# django debu toolbar config
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

trellowatch/apps/watcher/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
# Create your models here.

class TrelloTask(models.Model):
    """
    Model used to log cards awaiting replies
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    board_name = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=50)
    trello_card_id = models.CharField(max_length=30)
    last_activity = models.DateTimeField(default=timezone.now)
    accumulated_comments_since_my_last_action = models.IntegerField(default=0)
    is_awaiting_reply = models.BooleanField(default=True)

    def __str__(self):
        return self.title

class Board(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    board_trello_id = models.CharField(max_length=25)
    name = models.CharField(max_length=255)
    idOrganization = models.CharField(max_length=25)
    is_watched = models.BooleanField(default=False)
    webhook_id = models.CharField(max_length=25)

    def get_url(self):
        return "https://trello.com/b/" + self.board_id

    def __str__(self):
        return self.name

trellowatch/apps/watcher/views.py
from django.http import HttpResponse, HttpResponseForbidden
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.conf import settings

from ipaddress import ip_address, ip_network
import json, requests

from django.contrib.auth.models import User
from .models import Board, TrelloTask

import logging
logger = logging.getLogger("trellowatch")

@login_required
def board_list(request):
    if not request.user.social_auth.filter(provider='trello'):
        messages.error(request, 'You must be logged in with trello to access this page.')
        return redirect('/')
    board_list = list(Board.objects.filter(user=request.user).order_by('name'))
    context = {
        'board_list': board_list,
    }
    return render(request, 'watcher/board_list.html', context)


@login_required
def trello_task(request):
    if not request.user.social_auth.filter(provider='trello'):
        messages.error(request, 'You must be logged in with trello to access this page.')
        return redirect('/')
    trello_task = list(TrelloTask.objects.filter(user=request.user).filter(is_awaiting_reply=True))
    context = {
        'trello_task': trello_task,
    }
    return render(request, 'watcher/trello_task.html', context)


@login_required
def generate_board_list(request):
    if not request.user.social_auth.filter(provider='trello'):
        messages.error(request, 'You must be logged in with trello to access this page.')
        return redirect('/')

    social_user = request.user.social_auth.get(provider='trello')
    token = social_user.access_token['oauth_token']
    req = requests.get("https://api.trello.com/1/members/me/boards?key="+settings.SOCIAL_AUTH_TRELLO_KEY+"&token="+token)
    boards = req.json()

    created = 0
    for board in req.json():
        try:
            obj = Board.objects.get(
                board_trello_id=board['id'],
                user=request.user,
            )
            if obj.name != board['name']:
                obj.name = board['name']
                obj.save()
            if obj.idOrganization != board['idOrganization']:
                obj.idOrganization = board['idOrganization'] if board['idOrganization'] else ''
                obj.save()

        except Board.DoesNotExist:
            obj = Board(
                board_trello_id=board['id'],
                name=board['name'],
                user=request.user,
                idOrganization=board['idOrganization'] if board['idOrganization'] else '',
            )
            obj.save()
            created +=1

    messages.success(request, "Board list updated : {} new boards created".format(created))
    return redirect('watcher:board_list')

@login_required
def mute_this_task(request, task_id):
    task = TrelloTask.objects.get(id=task_id)
    task.is_awaiting_reply = False
    task.save()
    return redirect('watcher:trello_task')

@login_required
def update_watched_boards(request):
    logger.info('entered update_watched_boards')
    for key in request.POST:
        if "toggle_" in key:
            logger.debug("key: "+key)
            board_id = key.split("_")[1]
            board = get_object_or_404(Board, board_trello_id=board_id, user=request.user)

            social_user = request.user.social_auth.get(provider='trello')
            token = social_user.access_token['oauth_token']
            logger.debug("token"+token)

            if board.is_watched != (request.POST[key] == 'on'):
                # Submitted board status is different from db board status. 2 possibilities :
                #  - board.is_watched is False and request.POST[key] is on  -> we should setup the watch
                #  - board.is_watched is True  and request.POST[key] is off -> we should unset the watch
                logger.debug("The status of board \'{}\' has chanded".format(board.name))

                if not board.is_watched:
                    # we should setup the watch
                    logger.info("gonna post a new webhook!")
                    callbackURL = 'http://'+settings.CALLBACK_HOST+'/watcher/trelloCallback/'+str(request.user.id)
                    logger.debug('callbackURL : '+callbackURL)
                    parameters = {
                        'description': 'Webhook for trellowbeb for board {}'.format(board.name),
                        'callbackURL': callbackURL,
                        'idModel': board_id
                    }
                    post_url = "https://api.trello.com/1/webhooks/?key="+settings.SOCIAL_AUTH_TRELLO_KEY+"&token="+token
                    logger.debug("post_url: "+post_url)
                    r = requests.post(post_url, data=parameters)
                    logger.debug("post request response: "+r.text)
                    if r.status_code == 200:
                        board.webhook_id = r.json()['id']
                        board.is_watched = (request.POST[key] == 'on')
                        board.save()
                        messages.success(request, 'New settings were saved.')
                    else :
                        messages.success(request, 'There was a problem with your request.')



                else:
                    # we should unset the watch
                    logger.info("gonna destroy an existing webhook")
                    webhook_id = board.board_trello_id
                    logger.debug("webhook id is : {}".format(webhook_id))
                    r = requests.delete("https://api.trello.com/1/webhooks/"+webhook_id+"?key="+settings.SOCIAL_AUTH_TRELLO_KEY+"&token="+token)
                    logger.debug("deletion request response: " + r.text)
                    board.webhook_id = ""
                    board.is_watched = (request.POST[key] == 'on')
                    board.save()
                    messages.success(request, 'New settings were saved.')

    return redirect('watcher:board_list')


def check_request_is_from_trello(forwarded_for):
    client_ip_address = ip_address(forwarded_for)
    logger.debug('client_ip_address: {}'.format(client_ip_address))
    whitelist = [
        "107.23.104.115",
        "107.23.149.70",
        "54.152.166.250",
        "54.164.77.56",
    ]

    for valid_ip in whitelist:
        if client_ip_address in ip_network(valid_ip):
            logger.info("Request from Trello IP")
            break
    else:
        logger.info("Request from Unknown IP")
        return False

    return True


@csrf_exempt
def trello_webhook(request, user_id):
    if request.method == "HEAD":
        return HttpResponse("OK")

    forwarded_for = u'{}'.format(request.META.get('HTTP_X_FORWARDED_FOR'))
    logger.debug('forwarded_for: '+forwarded_for)
    if not check_request_is_from_trello(forwarded_for):
        logger.info("Access Denied, not from Trello")
        return HttpResponseForbidden("Access Denied, not from Trello")

    obj = request.body.decode("utf-8")
    data = json.loads(obj)
    action = data["action"]

    logger.debug('user_id: '+user_id)
    user = User.objects.get(id=user_id)
    username = user.social_auth.get(provider='trello').extra_data['username']
    logger.debug('trello username: ' +username)

    if action["type"] == "commentCard":
        logger.debug("Commented card")
        if username in action["data"]["text"]:
            logger.debug("ACHTUNG Mentionned me!")
            try:
                task = TrelloTask.objects.filter(user=user).get(trello_card_id=action["data"]["card"]["id"])
                task.accumulated_comments_since_my_last_action +=1
                task.is_awaiting_reply = True
                task.save()
            except (KeyError, TrelloTask.DoesNotExist):
                task = TrelloTask.objects.create(
                    user=user,
                    trello_card_id=action["data"]["card"]["id"],
                    board_name = action["data"]["board"]["name"],
                    title = action["data"]["card"]["name"],
                    author = action["memberCreator"]["username"],
                    accumulated_comments_since_my_last_action = 1,
                    is_awaiting_reply = True,
                )

        elif action["memberCreator"]["username"] == username:
            task = get_object_or_404(TrelloTask, trello_card_id=action["data"]["card"]["id"], user=user)
            task.is_awaiting_reply = False
            task.accumulated_comments_since_my_last_action = 0
            task.save()
        else:
            task = get_object_or_404(TrelloTask, trello_card_id=action["data"]["card"]["id"], user=user)
            task.accumulated_comments_since_my_last_action+=1
            task.save()

    return HttpResponse(status=200)

trellowatch/apps/watcher/templates/watcher/board_list.html
<!DOCTYPE html>
<html>
{% include 'watcher/head.html' %}

<body>
    {% include 'watcher/nav.html' %}
    <div class="container">


        <div class="row">
          <h1 class="text-center"> Monitoring Trello Boards </h1>
        </div>
        <div class="row">
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
          </div>
          {% endfor %}
        </div>

        <div class="row text-center">
            <a class="btn btn-info" href="{% url 'watcher:generate_board_list' %}" style="margin-bottom:20px;">refresh board list</a>
        </div>
        {% if board_list %}
        <form action="{% url 'watcher:update_watched_boards' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-6 col-lg-offset-3 col-sm-12">
                    <div class="table-responsive">


                        <table class="table table-bordered table-hover table-striped tablesorter">
                            <thead>
                                <tr>
                                    <th class="header"> Board Name <i class="icon-sort"></i></th>
                                    <th class="header"> Watching <i class="icon-sort"></i></th>
                                </tr>
                            </thead>
                            <tbody>



                                {% for board in board_list %}
                                <tr>
                                    <td> <a href="https://trello.com/b/{{ board.board_trello_id }}" target="_blank">{{board.name}}</a> </td>
                                    <td>
                                        <!-- Rounded switch -->
                                        <label class="switch">
                                            <input type="checkbox" name="toggle_{{ board.board_trello_id }}" id="toggle_{{ board.board_trello_id }}" {% if board.is_watched %}checked{% endif %}>
                                            <div class="slider round"></div>
                                        </label>
                                    </td>
                                </tr>
                                {% endfor %}


                            </tbody>
                        </table>


                    </div>
                </div>
            </div>
            <div class="row text-center" style='margin-bottom:150px;'>
              <input class="btn btn-primary" type="submit" value="Save" />
                <a class="btn btn-info" href="{% url 'watcher:generate_board_list' %}">refresh board list</a>
            </div>
        </form>

        {% else %}
        <p>No boards are available.</p>
        {% endif %}

    </div>
{% include 'watcher/footer.html' %}
</body>

<script type="text/javascript">
// Add an event listener on #form's submit action...
$("form").submit(
    function() {

        // For each unchecked checkbox on the form...
        $(this).find($("input:checkbox:not(:checked)")).each(

            // Create a hidden field with the same name as the checkbox and a value of 0
            // You could just as easily use "off", "false", or whatever you want to get
            // when the checkbox is empty.
            function(index) {
                var input = $('<input />');
                input.attr('type', 'hidden');
                input.attr('name', $(this).attr("name")); // Same name as the checkbox
                input.attr('value', "0"); // or 'off', 'false', 'no', whatever

                // append it to the form the checkbox is in just as it's being submitted
                var form = $(this)[0].form;
                $(form).append(input);

            }   // end function inside each()
        );      // end each() argument list

        return true;    // Don't abort the form submit

    }   // end function inside submit()
);      // end submit() argument list
</script>

</html>

trellowatch/apps/watcher/templates/watcher/footer.html
<footer class="footer">
  <div class="container">
    <p class="text-muted text-center">Made with ♥ by <a href="http://github.com/edelans" target="_blank" >edelans</a>. Fork me on <a href="https://gitlab.com/edelans/trellowatch" target="_blank" >gitlab</a> !</p>
  </div>
</footer>

trellowatch/apps/watcher/templates/watcher/head.html
<head>
  <title> TrelloWatch</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'watcher/style.css' %}" />
  <link rel="shortcut icon" href="{%  static 'img/favicon.ico' %}">
  <script src="/static/bower_components/jquery/dist/jquery.js"></script>
  <script type="text/javascript" src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

  <link rel="stylesheet" href="/static/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/bower_components/components-font-awesome/css/font-awesome.min.css">

</head>

trellowatch/apps/watcher/templates/watcher/nav.html
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">TrelloWatch</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-left">

              {% if user and not user.is_anonymous %}

              <li><a href="/watcher/board_list/">Settings</a></li>
              <li><a href="/watcher/trello_task/">Trello ToDo</a></li>

              {% endif %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
              {% if user and not user.is_anonymous %}

                <li>
                  <a>Hello {{ user.get_full_name|default:user.username }}!</a>
                </li>
                <li>
                  <a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>
                </li>

              {% else %}
                <li>
                  <a href="{% url 'social:begin' 'trello' %}?next={{ request.path }}">Login with Trello</a>
                </li>
              {% endif %}
            </ul>


        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

trellowatch/apps/watcher/templates/watcher/trello_task.html
<!DOCTYPE html>
<html>
{% include 'watcher/head.html' %}
<body>
  {% include 'watcher/nav.html' %}

  <div class="container">

    <h1 class="text-center"> Monitoring Trello Tasks </h1>

    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}


{% if trello_task %}
	<div class="col-sm-12">
        <div class="table-responsive">
            <table id="task_table" class="table table-bordered table-hover table-striped tablesorter">
                <thead>
                <tr>
                <th class="header"> Board Name <i class="icon-sort"></i></th>
                <th class="header"> Title <i class="icon-sort"></i></th>
                <th class="header"> Mentioner <i class="icon-sort"></i></th>
                <th class="header"> Last activity <i class="icon-sort"></i></th>
                <th class="header"> Accumulated comments <i class="icon-sort"></i></th>
                <th class="header"> Mute <i class="icon-sort"></i></th>
                </tr>
            </thead>
            <tbody>


            {% for task in trello_task %}
                <tr>

                    <td>{{task.board_name}}</td>
                    <td>
                      <a href="https://trello.com/c/{{task.trello_card_id}}" target="_blank">{{task.title}}</a>
                    </td>
                    <td>{{task.author}}</td>
                    <td>{{task.last_activity}}</td>
                    <td>{{task.accumulated_comments_since_my_last_action}}</td>
                    <td>
                      <span class="fa-stack fa-lg">
                        <a href="{% url 'watcher:mute_this_task' task_id=task.id %}">
                          <i class="fa fa-square-o fa-stack-2x"></i>
                          <i class="fa fa-volume-off fa-stack-1x"></i>
                        </a>
                      </span>
                    </td>
    			      </tr>
            {% endfor %}


            </tbody>
            </table>
        </div>
    </div>
    {% else %}
        <p>No task available.</p>

    {% endif %}
      </div>
{% include 'watcher/footer.html' %}

<!-- datables plugin -->
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.js"></script>

<script type="text/javascript">

function filterGlobal (datatable, myInput) {
  if (myInput.indexOf('-') == 0) {
    // filter out value when starting search input with '-'
    var filterValue = myInput.split('-')[1];
    filterOutRegex = '^((?!' + filterValue +').)*$';
    datatable.search(filterOutRegex, true, false).draw();
  } else {
    // https://datatables.net/reference/api/search()
    datatable.search(myInput, false, true).draw();
  }
}

$(document).ready( function () {
  var datatable = $('#task_table').DataTable({
    "pageLength": 50
  });

  $('input[type=search]').on( 'keyup click', function () {
      myInput = $('input[type=search]').val();
      filterGlobal(datatable, myInput);
  } );
} );




////////////////////////////////////////////////












$(document).ready(function() {
    $('#example').DataTable();




} );
</script>

</body>
</html>